GO
IF NOT EXISTS(SELECT *  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILERS' AND COLUMN_NAME = 'GST_NO')
 BEGIN
 ALTER TABLE [RETAILERS] ADD GST_NO VARCHAR(500)
 END;
 
 GO
 ALTER TABLE BILLINGS
ALTER COLUMN BILL_NO varchar(500)