//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILLING()
        {
            this.BILLING_INFO = new HashSet<BILLING_INFO>();
            this.BILLING_TAX_INFO = new HashSet<BILLING_TAX_INFO>();
        }
    
        public int ID { get; set; }
        public string BILL_NO { get; set; }
        public int RETAIL_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<long> CUST_MOBILE { get; set; }
        public Nullable<double> PAID_AMOUNT { get; set; }
        public Nullable<double> TAX_AMOUNT { get; set; }
        public Nullable<double> ACTUAL_AMOUNT { get; set; }
        public Nullable<double> BILLED_AMOUNT { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLING_INFO> BILLING_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLING_TAX_INFO> BILLING_TAX_INFO { get; set; }
        public virtual RETAILER RETAILER { get; set; }
    }
}
