//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int ID { get; set; }
        public int ITEM_ID { get; set; }
        public int RETAIL_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RETAILER RETAILER { get; set; }
        public virtual USER USER { get; set; }
    }
}
